<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Akusherlik va ginekologiya' => 'Obstetrics and gynecology',
    'Akusherlik va ginekologiya: Akusherlik va ginekologiya bo‘limi ayollarga har tomonlama yordam ko‘rsatadi, jumladan, prenatal parvarish, tug‘ruq, reproduktiv salomatlik, oilani rejalashtirish, ginekologik kasalliklarni davolash.' => 'Obstetrics and Gynecology: The Department of Obstetrics and Gynecology provides comprehensive care to women, including prenatal care, delivery, reproductive health, family planning, and gynecological treatment.',
    'Bemorga yo\'naltirilgan yondashuv: Biz bemorlarimizni hamma narsada birinchi o\'ringa qo\'yishga intilamiz.' => 'Patient-centered approach: We strive to put our patients first in everything we do.',
    'Biz haqimizda' => 'About us',
    'Bizning asosiy maqsadimiz' => 'Our main goal',
    'Bizning hamkorlar' => 'Our partners',
    'Bizning keng qamrovli sog\'liqni saqlash xizmatlarimizdan tashqari, tibbiyot birlashma muayyan ehtiyoj va imtiyozlarni qondirish uchun mo\'ljallangan yuqori darajadagi pullik xizmatlar tanlovini taklif etadi. Ushbu pullik xizmatlar kengaytirilgan qulaylik, shaxsiy parvarish va qo\'shimcha qulayliklarni ta\'minlash uchun mo\'ljallangan.' => 'In addition to our comprehensive health care services, the medical association offers a selection of premium paid services designed to meet specific needs and preferences. These paid services are designed to provide enhanced comfort, personal care and additional amenities.',
    'Bizning keng qamrovli xizmatlarimiz profilaktika yordami, diagnostika muolajalari, ilg`or muolajalar va ixtisoslashtirilgan davolash usullarini o`z ichiga oladi va bu sizning barcha sog`liqni saqlash ehtiyojlaringiz bir tom ostida qondirilishini ta`minlaydi.' => 'Our comprehensive range of services includes preventive care, diagnostic procedures, advanced procedures and specialized treatments, ensuring that all your healthcare needs are met under one roof.',
    'Bizning malakali shifokorlarimiz' => 'Our qualified doctors',
    'Bizning pullik xizmatlar' => 'Our paid services',
    'Bizning sog`liqni saqlash xizmatlarimiz' => 'Our healthcare services',
    'Our mission is to improve the health and quality of life of individuals and families through comprehensive and personalized medical services.' => '',
    'Bizning xizmatlar' => 'Our services',
    'Blog' => '',
    'Bo\'limlar' => 'Departments',
    'Bog`lanish' => 'Contacts',
    'Bolalar shifokori' => 'Pediatrician',
    'Dermatologiya' => 'Dermatology',
    'Dermatologiya bo`limi teri, soch va tirnoqlar bilan bog`liq kasalliklarni tashxislash va davolash bilan shug`ullanadi. U teri infektsiyalari, allergiya, dermatit, akne va teri saratoni kabi ko`plab muammolarni qamrab oladi.' => 'Department of Dermatology deals with diagnosis and treatment of diseases related to skin, hair and nails. It covers many problems such as skin infections, allergies, dermatitis, acne and skin cancer.',
    'Doimiy takomillashtirish: Biz doimiy takomillashtirish madaniyatiga sodiqmiz. Bizning maqsadimiz o\'z faoliyatini muntazam ravishda baholashdir' => 'Continuous Improvement: We are committed to a culture of continuous improvement. Our goal is to regularly evaluate your performance',
    'Elektron pochta' => 'Email',
    'Eng so\'nngi yangliklar' => 'Latest news',
    'Hamkorlar' => 'Partners',
    'Infeksiologiya' => 'Infectiology',
    'Innovatsiyalar va texnologiyalarni qamrab olish: Biz tibbiy yutuqlar va texnologik innovatsiyalarning oldingi saflarida qolishga intilamiz.' => 'Embracing Innovation and Technology: We strive to stay at the forefront of medical advances and technological innovation.',
    'Keng qamrovli va favqulodda sog\'liqni saqlash xizmatlarini taqdim etish missiyamizda biz boshqa sog\'liqni saqlash provayderlari, tashkilotlari va manfaatdor tomonlar bilan mustahkam hamkorlik o\'rnatish muhimligini tan olamiz.' => 'In our mission to provide comprehensive and exceptional healthcare services, we recognize the importance of building strong partnerships with other healthcare providers, organizations and stakeholders.',
    'Manzil' => 'Address',
    'Mijozlarimiz biz haqimizda qanday fikrda?' => 'What our clients say about us?',
    'Mijozlarimiz fikrlari' => 'Feedbacks',
    'Nevrologiya' => 'Neurology',
    'Nevrologiya bo`limi asab tizimining, jumladan, miya, orqa miya va periferik nervlarning buzilishlari bilan shug`ullanadi. U insult, epilepsiya, Parkinson kasalligi va ko`p skleroz kabi kasalliklarni tashxislash va boshqarishga qaratilgan.' => 'The Department of Neurology deals with disorders of the nervous system, including the brain, spinal cord, and peripheral nerves. It focuses on the diagnosis and management of diseases such as stroke, epilepsy, Parkinson\'s disease and multiple sclerosis.',
    'Oilaviy poliklinika' => 'Family polyclinic',
    'Ortopediya' => 'Orthopedics',
    'Ortopediya bo`limi suyak sinishi, bo`g`imlarning buzilishi, sport jarohatlari va degenerativ kasalliklarni o`z ichiga olgan tayanch-harakat tizimi kasalliklarini tashxislash va davolashga ixtisoslashgan.' => 'The Department of Orthopedics specializes in the diagnosis and treatment of diseases of the musculoskeletal system, including bone fractures, joint disorders, sports injuries and degenerative diseases.',
    'Shifoxonamizda bizning maqsadlarimiz alohida tibbiy xizmatlar ko\'rsatish va bemorlarimizning umumiy farovonligini yaxshilashga qaratilgan. Mana bizning asosiy maqsadlarimiz:' => 'At our hospital, our goals are to provide exceptional medical services and improve the overall well-being of our patients. Here are our main goals:',
    'Shifoxonamizdagi yuqori malakali va fidoyi shifokorlarimiz jamoasi har bir bemorga alohida tibbiy yordam ko\'rsatish va shaxsiy e\'tiborni taqdim etishga intiladi. Turli mutaxassisliklar va boy tajribaga ega bo\'lgan shifokorlarimiz eng yuqori sifatli tibbiy xizmatlarni taqdim etishga ishtiyoqlidir.' => 'Our team of highly qualified and dedicated doctors at our hospital strives to provide individual medical care and personal attention to each patient. Our doctors with various specialties and rich experience are passionate about providing the highest quality medical services.',
    'Shifoxonamizdan soʻnggi yangiliklar va yangilanishlardan xabardor boʻling. Bizning yangiliklar bo\'limimiz yangi xizmatlar, tibbiy yutuqlar, jamoat tadbirlari va muhim e\'lonlar haqida qimmatli ma\'lumotlarni taqdim etadi.' => 'Stay up to date with the latest news and updates from our hospital. Our news section provides valuable information about new services, medical advances, community events and important announcements.',
    'Shifoxonamizga xush kelibsiz ' => 'Welcome to our hospital',
    'Shifoxonamizga xush kelibsiz, bu yerda sog`ligingiz bizning ustuvor vazifamizdir. Biz sizning tibbiy ehtiyojlaringiz uchun to`g`ri shifoxonani tanlash juda muhim qaror ekanligini tushunamiz va nima uchun biz sizning ishonchli tibbiy xizmat ko`rsatuvchi provayderingiz bo`lishimiz kerakligini ko`rsatish uchun shu yerdamiz.' => 'Welcome to our hospital, where your health is our priority. We understand that choosing the right hospital for your medical needs is a very important decision, and we are here to show you why we should be your trusted healthcare provider.',
    'Shoshilinch tibbiy yordam bo\'limi o\'tkir kasalliklar, jarohatlar va tibbiy favqulodda vaziyatlarda zudlik bilan tibbiy yordam ko\'rsatadi. U 24/7 ishlaydi va ko\'plab shoshilinch tibbiy sharoitlarni ko\'rib chiqish uchun jihozlangan.' => 'The emergency department provides immediate medical care for acute illnesses, injuries, and medical emergencies. It operates 24/7 and is equipped to handle a wide range of medical emergencies.',
    'Sifatli xizmat ko`rsatish' => 'Quality service',
    'Telefon raqam' => 'Phone',
    'Tez tibbiy yordam' => 'Emergency medical assistance',
    'Tezkor havolalar' => 'Quick links',
    'Tezkor ro`yxatga olish' => 'Quick registration',
    'Tezkor tahlil natijasi' => 'Quick analysis result',
    'Umumiy shifokor' => 'General doctor',
    'Xizmatlar' => 'Services',
    'Xodimlar' => 'Doctors',
    'Yangiliklar' => 'News',
    'Yuqori sifatli yordam ko\'rsatish: Bizning asosiy maqsadimiz bemorlarimizga eng yuqori standartdagi yordamni taqdim etishdir.' => 'Providing high-quality care: Our main goal is to provide the highest standard of care to our patients.',
    'Yuqumli kasalliklar bo\'limi bakteriyalar, viruslar, zamburug\'lar va parazitlar kabi mikroorganizmlar keltirib chiqaradigan kasalliklarning oldini olish, tashxislash va davolashga qaratilgan. Ushbu bo\'lim yuqumli kasalliklar tarqalishini boshqarish va nazorat qilishda hal qiluvchi rol o\'ynaydi.' => 'The Department of Infectious Diseases focuses on the prevention, diagnosis and treatment of diseases caused by microorganisms such as bacteria, viruses, fungi and parasites. This department plays a crucial role in managing and controlling the spread of infectious diseases.',
    'Kontaktlar' => 'Contacts',
    'Shifokor bilan uchrashuv' => 'Appointment with doctor',
    'Murojaatingizni Qoldiring' => 'Leave your request',
    'Sizga taqdim etadigan xizmatlarimiz' => 'Our services for you',
    'Bosh sahifa' => 'Home',
    'Onlayn konsultatsiya' => 'Online consult',
    'Siz bilan 24/7 aloqadamiz' => 'We are in touch  with you 24/7',
    "Bizning shifoxonamiz bemorlarimizga qulay va qulay tibbiy xizmatlarni taqdim etishga intiladi. Bemor tajribasini oshirishga bag'ishlashimizning bir qismi sifatida biz eng zamonaviy onlayn maslahat vositalarini taklif etamiz." => 'Our hospital strives to provide comfortable and convenient medical services to our patients. As part of our dedication to improving the patient experience, we offer state-of-the-art online consultation tools.',

    'Online uchrashuvlar' => 'Online meetings',
    'Xavfsiz va maxfiy' => 'Safe and secret',
    'Elektron retseptlar' => 'e-recepts',
    'Raqamli tibbiy hisobotlar' => 'Digital medical reports',
    'Foydalanish imkoniyati va qulaylik' => 'Usability and convenience',
    "Biz bilan bog'laning" => 'Contact with us',
    "Murojaatingizni qoldiring" => 'Leave your message',
    "Ism"=>"Name",
    "Familiya"=>"Surname",
    "Murojaat mavzusi"=>"Title of message",
    "Murojaat matni"=>"Body of message",
    "Murojaatni yuborish"=>"Send message",
    "Namangan shahar tibbiyot birlashmasi" => "Namangan City Medical Association",
    'Bizning vazifamiz har tomonlama va shaxsiylashtirilgan tibbiy xizmatlar orqali odamlar va oilalar salomatligi va hayot sifatini yaxshilashdir.' =>'Our mission is to improve the health and quality of life of individuals and families through comprehensive and personalized medical services.',



];
