<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Novosti',
    'Akusherlik va ginekologiya' => 'Акушерство и гинекология',
    'Akusherlik va ginekologiya: Akusherlik va ginekologiya bo‘limi ayollarga har tomonlama yordam ko‘rsatadi, jumladan, prenatal parvarish, tug‘ruq, reproduktiv salomatlik, oilani rejalashtirish, ginekologik kasalliklarni davolash.' => 'Акушерство и гинекология: Отделение акушерства и гинекологии оказывает всестороннюю помощь женщинам, включая дородовой уход, роды, репродуктивное здоровье, планирование семьи и гинекологическую помощь.',
    'Bemorga yo\'naltirilgan yondashuv: Biz bemorlarimizni hamma narsada birinchi o\'ringa qo\'yishga intilamiz.' => 'Подход, ориентированный на пациента: мы стремимся ставить наших пациентов на первое место во всем, что мы делаем.',
    'Biz haqimizda' => 'O нас',
    'Bizning asosiy maqsadimiz' => 'Наша главная цель',
    'Bizning hamkorlar' => 'Наши партнеры',
    'Bizning keng qamrovli sog\'liqni saqlash xizmatlarimizdan tashqari, tibbiyot birlashma muayyan ehtiyoj va imtiyozlarni qondirish uchun mo\'ljallangan yuqori darajadagi pullik xizmatlar tanlovini taklif etadi. Ushbu pullik xizmatlar kengaytirilgan qulaylik, shaxsiy parvarish va qo\'shimcha qulayliklarni ta\'minlash uchun mo\'ljallangan.' => 'В дополнение к нашим комплексным медицинским услугам медицинская ассоциация предлагает ряд платных услуг премиум-класса, предназначенных для удовлетворения конкретных потребностей и предпочтений. Эти платные услуги предназначены для обеспечения повышенного комфорта, личного ухода и дополнительных удобств.',
    'Bizning keng qamrovli xizmatlarimiz profilaktika yordami, diagnostika muolajalari, ilg`or muolajalar va ixtisoslashtirilgan davolash usullarini o`z ichiga oladi va bu sizning barcha sog`liqni saqlash ehtiyojlaringiz bir tom ostida qondirilishini ta`minlaydi.' => 'Наш широкий спектр услуг включает в себя профилактику, диагностические процедуры, передовые процедуры и специализированное лечение, гарантируя, что все ваши медицинские потребности будут удовлетворены под одной крышей.',
    'Bizning malakali shifokorlarimiz' => 'Наши квалифицированные врачи',
    'Bizning pullik xizmatlar' => 'Наши платные услуги',
    'Bizning sog`liqni saqlash xizmatlarimiz' => 'Наши медицинские услуги',
    'Bizning vazifamiz har tomonlama va shaxsiylashtirilgan tibbiy xizmatlar orqali odamlar va oilalar salomatligi va hayot sifatini yaxshilashdir. ' => 'Наша миссия заключается в улучшении здоровья и качества жизни отдельных лиц и семей с помощью комплексных и персонализированных медицинских услуг.',
    'Bizning xizmatlar' => 'Наши сервисы',
    'Bo\'limlar' => 'Департаменты',
    'Bog`lanish' => 'Контакты',
    'Bolalar shifokori' => 'Педиатр',
    'Dermatologiya' => 'Дерматология',
    'Dermatologiya bo`limi teri, soch va tirnoqlar bilan bog`liq kasalliklarni tashxislash va davolash bilan shug`ullanadi. U teri infektsiyalari, allergiya, dermatit, akne va teri saratoni kabi ko`plab muammolarni qamrab oladi.' => 'Отделение дерматологии занимается диагностикой и лечением заболеваний кожи, волос и ногтей. Он охватывает многие проблемы, такие как кожные инфекции, аллергии, дерматиты, прыщи и рак кожи.',
    'Doimiy takomillashtirish: Biz doimiy takomillashtirish madaniyatiga sodiqmiz. Bizning maqsadimiz o\'z faoliyatini muntazam ravishda baholashdir' => 'Непрерывное совершенствование: мы привержены культуре постоянного совершенствования. Наша цель - регулярно оценивать вашу работу',
    'Elektron pochta' => 'Электрон почта',
    'Eng so\'nngi yangliklar' => 'Последние новости',
    'Hamkorlar' => 'Партнеры',
    'Infeksiologiya' => 'Инфекционная',
    'Innovatsiyalar va texnologiyalarni qamrab olish: Biz tibbiy yutuqlar va texnologik innovatsiyalarning oldingi saflarida qolishga intilamiz.' => 'Использование инноваций и технологий: мы стремимся оставаться в авангарде медицинских достижений и технологических инноваций.',
    'Keng qamrovli va favqulodda sog\'liqni saqlash xizmatlarini taqdim etish missiyamizda biz boshqa sog\'liqni saqlash provayderlari, tashkilotlari va manfaatdor tomonlar bilan mustahkam hamkorlik o\'rnatish muhimligini tan olamiz.' => 'В нашей миссии по предоставлению комплексных и исключительных медицинских услуг мы признаем важность построения прочных партнерских отношений с другими поставщиками медицинских услуг, организациями и заинтересованными сторонами.',
    'Manzil' => 'Адрес',
    'Mijozlarimiz biz haqimizda qanday fikrda?' => 'Что наши клиенты думают о нас?',
    'Mijozlarimiz fikrlari' => 'Мнения наших клиентов',
    'Nevrologiya' => 'неврология',
    'Nevrologiya bo`limi asab tizimining, jumladan, miya, orqa miya va periferik nervlarning buzilishlari bilan shug`ullanadi. U insult, epilepsiya, Parkinson kasalligi va ko`p skleroz kabi kasalliklarni tashxislash va boshqarishga qaratilgan.' => 'Отделение неврологии занимается заболеваниями нервной системы, в том числе головного и спинного мозга и периферических нервов. Основное внимание уделяется диагностике и лечению таких заболеваний, как инсульт, эпилепсия, болезнь Паркинсона и рассеянный склероз.',
    'Oilaviy poliklinika' => 'Семейная поликлиника',
    'Ortopediya' => 'Ортопедия',
    'Ortopediya bo`limi suyak sinishi, bo`g`imlarning buzilishi, sport jarohatlari va degenerativ kasalliklarni o`z ichiga olgan tayanch-harakat tizimi kasalliklarini tashxislash va davolashga ixtisoslashgan.' => 'Отделение ортопедии специализируется на диагностике и лечении заболеваний опорно-двигательного аппарата, в том числе переломов костей, заболеваний суставов, спортивных травм и дегенеративных заболеваний.',
    'Shifoxonamizda bizning maqsadlarimiz alohida tibbiy xizmatlar ko\'rsatish va bemorlarimizning umumiy farovonligini yaxshilashga qaratilgan. Mana bizning asosiy maqsadlarimiz:' => 'В нашей больнице мы стремимся предоставлять исключительные медицинские услуги и улучшать общее самочувствие наших пациентов. Вот наши основные цели:',
    'Shifoxonamizdagi yuqori malakali va fidoyi shifokorlarimiz jamoasi har bir bemorga alohida tibbiy yordam ko\'rsatish va shaxsiy e\'tiborni taqdim etishga intiladi. Turli mutaxassisliklar va boy tajribaga ega bo\'lgan shifokorlarimiz eng yuqori sifatli tibbiy xizmatlarni taqdim etishga ishtiyoqlidir.' => 'Наша команда высококвалифицированных и преданных своему делу врачей в нашей больнице стремится обеспечить индивидуальный медицинский уход и персональное внимание к каждому пациенту. Наши врачи различных специальностей и с богатым опытом увлечены оказанием медицинских услуг самого высокого качества.',
    'Shifoxonamizdan soʻnggi yangiliklar va yangilanishlardan xabardor boʻling. Bizning yangiliklar bo\'limimiz yangi xizmatlar, tibbiy yutuqlar, jamoat tadbirlari va muhim e\'lonlar haqida qimmatli ma\'lumotlarni taqdim etadi.' => 'Будьте в курсе последних новостей и обновлений нашей больницы. Наш раздел новостей содержит ценную информацию о новых услугах, медицинских достижениях, общественных мероприятиях и важных объявлениях.',
    'Shifoxonamizga xush kelibsiz ' => 'Добро пожаловать в нашу больницу',
    'Shifoxonamizga xush kelibsiz, bu yerda sog`ligingiz bizning ustuvor vazifamizdir. Biz sizning tibbiy ehtiyojlaringiz uchun to`g`ri shifoxonani tanlash juda muhim qaror ekanligini tushunamiz va nima uchun biz sizning ishonchli tibbiy xizmat ko`rsatuvchi provayderingiz bo`lishimiz kerakligini ko`rsatish uchun shu yerdamiz.' => 'Добро пожаловать в нашу больницу, где ваше здоровье является нашим приоритетом. Мы понимаем, что выбор больницы, соответствующей вашим медицинским потребностям, является очень важным решением, и мы здесь, чтобы показать вам, почему мы должны быть вашим надежным поставщиком медицинских услуг.',
    'Shoshilinch tibbiy yordam bo\'limi o\'tkir kasalliklar, jarohatlar va tibbiy favqulodda vaziyatlarda zudlik bilan tibbiy yordam ko\'rsatadi. U 24/7 ishlaydi va ko\'plab shoshilinch tibbiy sharoitlarni ko\'rib chiqish uchun jihozlangan.' => '',
    'Sifatli xizmat ko`rsatish' => 'Качественное обслуживание',
    'Telefon raqam' => 'Номер телефона',
    'Tez tibbiy yordam' => 'Неотложная медицинская помощь',
    'Tezkor havolalar' => 'Быстрые ссылки',
    'Tezkor ro`yxatga olish' => 'Быстрая регистрация',
    'Tezkor tahlil natijasi' => 'Быстрый результат анализа',
    'Umumiy shifokor' => 'Врач общей практики',
    'Xizmatlar' => 'Сервисы',
    'Xodimlar' => 'Сотрудники',
    'Yangiliklar' => 'Новости',
    'Yuqori sifatli yordam ko\'rsatish: Bizning asosiy maqsadimiz bemorlarimizga eng yuqori standartdagi yordamni taqdim etishdir.' => 'Предоставление высококачественной медицинской помощи: Наша главная цель — обеспечить высочайший стандарт медицинской помощи для наших пациентов.',
    'Yuqumli kasalliklar bo\'limi bakteriyalar, viruslar, zamburug\'lar va parazitlar kabi mikroorganizmlar keltirib chiqaradigan kasalliklarning oldini olish, tashxislash va davolashga qaratilgan. Ushbu bo\'lim yuqumli kasalliklar tarqalishini boshqarish va nazorat qilishda hal qiluvchi rol o\'ynaydi.' => 'Отделение инфекционных болезней занимается профилактикой, диагностикой и лечением заболеваний, вызванных такими микроорганизмами, как бактерии, вирусы, грибки и паразиты. Этот отдел играет решающую роль в управлении и сдерживании распространения инфекционных заболеваний.',
    'Test' => '@@Testi@@',

    'Malakali Shifokorlar' => "Квалифицированные врачи",
    'Online foydalanuvchilar' => "Онлайн-пользователи",
    'Yuqori sifat' => "Высокое качество",
    'Yillik tajriba' => "Годы опыта",
    'Shikoyat qoldirish' => "Оставить жалобу",
    'Online uchrashuvlar' => "Онлайн встречи",
    'Onlayn konsultatsiya' => "Онлайн консультация",
    'Siz bilan 24/7 aloqadamiz' => "Мы с вами 24/7",
    "Bizning shifoxonamiz bemorlarimizga qulay va qulay tibbiy xizmatlarni taqdim etishga intiladi. Bemor tajribasini oshirishga bag'ishlashimizning bir qismi sifatida biz eng zamonaviy onlayn maslahat vositalarini taklif etamiz." => "Наша больница стремится предоставлять комфортные и удобные медицинские услуги нашим пациентам. Стремясь улучшить качество обслуживания пациентов, мы предлагаем современные инструменты онлайн-консультаций.",
    'Xavfsiz va maxfiy' => "Безопасно и конфиденциально",
    'Elektron retseptlar' => "Электронные рецепты",
    'Raqamli tibbiy hisobotlar' => "Цифровые медицинские отчеты",
    'Foydalanish imkoniyati va qulaylik' => "Юзабилити и удобств",
    'Bosh sahifa' => "Главная",
    'Kontaktlar' => "Kонтакты",
    'Shifokor bilan uchrashuv' => "На прием к врачу",
    'Murojaatingizni Qoldiring' => "Оставьте свой запрос"



];
