<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Yangiliklar',
    'Akusherlik va ginekologiya' => '',
    'Akusherlik va ginekologiya: Akusherlik va ginekologiya bo‘limi ayollarga har tomonlama yordam ko‘rsatadi, jumladan, prenatal parvarish, tug‘ruq, reproduktiv salomatlik, oilani rejalashtirish, ginekologik kasalliklarni davolash.' => '',
    'Bemorga yo\'naltirilgan yondashuv: Biz bemorlarimizni hamma narsada birinchi o\'ringa qo\'yishga intilamiz.' => '',
    'Biz haqimizda' => '',
    'Bizning asosiy maqsadimiz' => '',
    'Bizning hamkorlar' => '',
    'Bizning keng qamrovli sog\'liqni saqlash xizmatlarimizdan tashqari, tibbiyot birlashma muayyan ehtiyoj va imtiyozlarni qondirish uchun mo\'ljallangan yuqori darajadagi pullik xizmatlar tanlovini taklif etadi. Ushbu pullik xizmatlar kengaytirilgan qulaylik, shaxsiy parvarish va qo\'shimcha qulayliklarni ta\'minlash uchun mo\'ljallangan.' => '',
    'Bizning keng qamrovli xizmatlarimiz profilaktika yordami, diagnostika muolajalari, ilg`or muolajalar va ixtisoslashtirilgan davolash usullarini o`z ichiga oladi va bu sizning barcha sog`liqni saqlash ehtiyojlaringiz bir tom ostida qondirilishini ta`minlaydi.' => '',
    'Bizning malakali shifokorlarimiz' => '',
    'Bizning pullik xizmatlar' => '',
    'Bizning sog`liqni saqlash xizmatlarimiz' => '',
    'Bizning vazifamiz har tomonlama va shaxsiylashtirilgan tibbiy xizmatlar orqali odamlar va oilalar salomatligi va hayot sifatini yaxshilashdir. ' => '',
    'Bizning xizmatlar' => '',
    'Bo\'limlar' => '',
    'Bog`lanish' => '',
    'Bolalar shifokori' => '',
    'Dermatologiya' => '',
    'Dermatologiya bo`limi teri, soch va tirnoqlar bilan bog`liq kasalliklarni tashxislash va davolash bilan shug`ullanadi. U teri infektsiyalari, allergiya, dermatit, akne va teri saratoni kabi ko`plab muammolarni qamrab oladi.' => '',
    'Doimiy takomillashtirish: Biz doimiy takomillashtirish madaniyatiga sodiqmiz. Bizning maqsadimiz o\'z faoliyatini muntazam ravishda baholashdir' => '',
    'Elektron pochta' => '',
    'Eng so\'nngi yangliklar' => '',
    'Hamkorlar' => '',
    'Infeksiologiya' => '',
    'Innovatsiyalar va texnologiyalarni qamrab olish: Biz tibbiy yutuqlar va texnologik innovatsiyalarning oldingi saflarida qolishga intilamiz.' => '',
    'Keng qamrovli va favqulodda sog\'liqni saqlash xizmatlarini taqdim etish missiyamizda biz boshqa sog\'liqni saqlash provayderlari, tashkilotlari va manfaatdor tomonlar bilan mustahkam hamkorlik o\'rnatish muhimligini tan olamiz.' => '',
    'Manzil' => '',
    'Mijozlarimiz biz haqimizda qanday fikrda?' => '',
    'Mijozlarimiz fikrlari' => '',
    'Nevrologiya' => '',
    'Nevrologiya bo`limi asab tizimining, jumladan, miya, orqa miya va periferik nervlarning buzilishlari bilan shug`ullanadi. U insult, epilepsiya, Parkinson kasalligi va ko`p skleroz kabi kasalliklarni tashxislash va boshqarishga qaratilgan.' => '',
    'Oilaviy poliklinika' => '',
    'Ortopediya' => '',
    'Ortopediya bo`limi suyak sinishi, bo`g`imlarning buzilishi, sport jarohatlari va degenerativ kasalliklarni o`z ichiga olgan tayanch-harakat tizimi kasalliklarini tashxislash va davolashga ixtisoslashgan.' => '',
    'Shifoxonamizda bizning maqsadlarimiz alohida tibbiy xizmatlar ko\'rsatish va bemorlarimizning umumiy farovonligini yaxshilashga qaratilgan. Mana bizning asosiy maqsadlarimiz:' => '',
    'Shifoxonamizdagi yuqori malakali va fidoyi shifokorlarimiz jamoasi har bir bemorga alohida tibbiy yordam ko\'rsatish va shaxsiy e\'tiborni taqdim etishga intiladi. Turli mutaxassisliklar va boy tajribaga ega bo\'lgan shifokorlarimiz eng yuqori sifatli tibbiy xizmatlarni taqdim etishga ishtiyoqlidir.' => '',
    'Shifoxonamizdan soʻnggi yangiliklar va yangilanishlardan xabardor boʻling. Bizning yangiliklar bo\'limimiz yangi xizmatlar, tibbiy yutuqlar, jamoat tadbirlari va muhim e\'lonlar haqida qimmatli ma\'lumotlarni taqdim etadi.' => '',
    'Shifoxonamizga xush kelibsiz ' => '',
    'Shifoxonamizga xush kelibsiz, bu yerda sog`ligingiz bizning ustuvor vazifamizdir. Biz sizning tibbiy ehtiyojlaringiz uchun to`g`ri shifoxonani tanlash juda muhim qaror ekanligini tushunamiz va nima uchun biz sizning ishonchli tibbiy xizmat ko`rsatuvchi provayderingiz bo`lishimiz kerakligini ko`rsatish uchun shu yerdamiz.' => '',
    'Shoshilinch tibbiy yordam bo\'limi o\'tkir kasalliklar, jarohatlar va tibbiy favqulodda vaziyatlarda zudlik bilan tibbiy yordam ko\'rsatadi. U 24/7 ishlaydi va ko\'plab shoshilinch tibbiy sharoitlarni ko\'rib chiqish uchun jihozlangan.' => '',
    'Sifatli xizmat ko`rsatish' => '',
    'Telefon raqam' => '',
    'Tez tibbiy yordam' => '',
    'Tezkor havolalar' => '',
    'Tezkor ro`yxatga olish' => '',
    'Tezkor tahlil natijasi' => '',
    'Umumiy shifokor' => '',
    'Xizmatlar' => '',
    'Xodimlar' => '',
    'Yangiliklar' => '',
    'Yuqori sifatli yordam ko\'rsatish: Bizning asosiy maqsadimiz bemorlarimizga eng yuqori standartdagi yordamni taqdim etishdir.' => '',
    'Yuqumli kasalliklar bo\'limi bakteriyalar, viruslar, zamburug\'lar va parazitlar kabi mikroorganizmlar keltirib chiqaradigan kasalliklarning oldini olish, tashxislash va davolashga qaratilgan. Ushbu bo\'lim yuqumli kasalliklar tarqalishini boshqarish va nazorat qilishda hal qiluvchi rol o\'ynaydi.' => '',
    'Test' => '@@Sinov@@',
    'Malakali Shifokorlar' => "",
];
